### ISSUE TITLE
API Response slow

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-api#104]
It is slow especially when the api hasn't accessed in a while.

Is it a case of keen fly server on? 

If that's the case, can we have production stayed on?

**Comment by hsb1007** [comment]
I have pushed temporary change for now but I am facing CICD failure, which I created a ticket for

**Comment by rajdip-b** [comment]
> It is slow especially when the api hasn't accessed in a while.
> 
> Is it a case of keen fly server on?
> 
> If that's the case, can we have production stayed on?

Yes exactly, this is a case of hot and cold boot. I don't think the prod one will go down so easily as and when the user rises. So, maybe we don't need to worry much about that!

**Comment by hsb1007** [comment]
For now let's keep the production on!  but staging to be auto-turned off!   right now based on my commit, both production and staging will be turned on! 

We want the app to be responsive when people visit now!

**Comment by rajdip-b** [comment]
Fixed
