### ISSUE TITLE
Update authnetication flow

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-api#105]
I have brought this from 
https://github.com/eronka/culero-api/issues/76

How critical is this?

We will need to make the following changes to the auth flow, specifically in auth.service.ts

We want to keep email verification localized only to email+password signup. So, we can move the check of user.isEmailVerified in the signIn function
In the createUserIfNotExists function, set isEmailVerified to true if the authType is not EMAIL

**Comment by hsb1007** [comment]
@rajdip-b  Any thought?

**Comment by rajdip-b** [comment]
I remember proposing this a while back! I'll get on to it asap.
