### ISSUE TITLE
Get Rate / Review response needs reviewing

### ISSUE THREAD

**Issue by hsb1007** [eronka/culero-api#80]
This is when I do

api/user/ratings/{userId}

And it doesn't have any user information in the response. It should includes the users who left the review or anonymous user if rate was created as anonymous

<img width="439" alt="image" src="https://github.com/eronka/culero-api/assets/4149765/033ad758-dca3-4a35-87a0-d795cec08bc6">

In comparison, when post rates for users, below is what I get. 

<img width="493" alt="image" src="https://github.com/eronka/culero-api/assets/4149765/c3f7bba2-9e39-44d3-aabd-0e953757ee79">

**Comment by Gmin2** [comment]
can i get assigned ?
